zip: Completely drop non-treble support and upstream AnyKernel2
Signed-off-by: Vipul Jha <vipuljha08@gmail.com>

diff --git a/zip/META-INF/com/google/android/update-binary b/zip/META-INF/com/google/android/update-binary
--- a/zip/META-INF/com/google/android/update-binary
+++ b/zip/META-INF/com/google/android/update-binary
@@ -1,5 +1,5 @@
 #!/sbin/sh
-# AnyKernel2 Backend
+# AnyKernel2 Backend (DO NOT CHANGE)
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
@@ -13,15 +13,20 @@ ui_print() {
   done;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
-file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
-if [ ! "$(getprop 2>/dev/null)" ]; then
-  getprop() {
-    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
-    test "$propval" || local propval="$(file_getprop $root/system/build.prop $1 2>/dev/null)";
-    test "$propval" && echo "$propval" || echo "";
-  }
-fi;
-cleanup() { rm -rf /tmp/anykernel; }
+file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
+int2ver() {
+  if [ "$1" -eq "$1" ] 2>/dev/null; then 
+    echo "$1.0.0";
+  elif [ ! "$(echo "$1" | $bb cut -d. -f3)" ]; then
+    echo "$1.0";
+  else
+    echo "$1";
+  fi;
+}
+cleanup() {
+  cd /tmp;
+  rm -rf /tmp/anykernel;
+}
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
@@ -31,6 +36,7 @@ debugging() {
     ;;
   esac;
 }
+is_mounted() { $bb mount | $bb grep " $1 "; }
 unmount_all() {
   (umount /system;
   if [ -d /system_root -a ! -f /system/build.prop ]; then
@@ -43,7 +49,7 @@ unmount_all() {
 abort() {
   ui_print "$*";
   debugging;
-  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
+  if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
   unmount_all;
@@ -56,26 +62,26 @@ cleanup;
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
 unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
+if [ $? != 0 -o -z "$(ls tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
 bb=/tmp/anykernel/tools/busybox;
 chmod 755 $bb;
-$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+$bb chmod -R 755 tools bin;
 
-if [ -f /tmp/anykernel/banner ]; then
+if [ -f banner ]; then
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
     ui_print "$line";
-  done < /tmp/anykernel/banner;
+  done < banner;
   ui_print " ";
   ui_print " ";
 fi;
 
-if [ -f /tmp/anykernel/version ]; then
+if [ -f version ]; then
   ui_print " ";
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
     ui_print "$line";
-  done < /tmp/anykernel/version;
+  done < version;
   ui_print " ";
 fi;
 ui_print "=================================";
@@ -94,106 +100,127 @@ ui_print "=================================";
 ui_print " ";
 
 unmount_all;
-mount -o ro -t auto /system;
-mount -o ro -t auto /vendor 2>/dev/null;
-mount /data 2>/dev/null;
-test -f /system/system/build.prop && root=/system;
-
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  # ui_print "Checking device...";
-  device="$(getprop ro.product.device)";
-  product="$(getprop ro.build.product)";
-  for i in 1 2 3 4 5; do
-    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
-    test "$testname" || break;
-    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
-      # ui_print "$testname";
-      match=1;
-      break;
-    fi;
-  done;
-  if [ "$match" != 1 ]; then
-    abort "Unsupported device. Aborting...";
-  fi;
-  # ui_print "Checking Android version...";
-  romsdk="$(file_getprop /system/build.prop ro.build.version.sdk)";
-  for i in 1 2; do
-    testsdk="$(file_getprop /tmp/anykernel/anykernel.sh supported.sdk$i)";
-    if [ "$romsdk" == "$testsdk" ]; then
-      # ui_print "sdk$testsdk";
-      matchsdk=1;
-      break;
-    fi;
-  done;
-  ui_print " ";
-  if [ "$matchsdk" != 1 ]; then
-    abort "Unsupported Android version. Aborting...":
-  fi;
-  if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
-    dtb=/tmp/anykernel/treble;
-  else
-    dtb=/tmp/anykernel/nontreble;
-  fi;
+if [ ! "$(is_mounted /system)" ]; then
+  $bb mount -o ro -t auto /system;
 fi;
-
+($bb mount -o ro -t auto /vendor;
+$bb mount /data) 2>/dev/null;
 if [ -f /system/system/build.prop ]; then
   umount /system;
-  umount /system 2>/dev/null;
-  mkdir /system_root 2>/dev/null;
-  mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
-  mount -o bind /system_root/system /system;
-  unset root;
+  (umount /system;
+  mkdir /system_root) 2>/dev/null;
+  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+  $bb mount -o bind /system_root/system /system;
 fi;
 savedpath="$LD_LIBRARY_PATH";
 savedpre="$LD_PRELOAD";
 unset LD_LIBRARY_PATH;
 unset LD_PRELOAD;
 
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
+elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.product 2>/dev/null)" ]; then
+  getprop() {
+    ($(which getprop) | $bb grep "$1" | $bb cut -d[ -f3 | $bb cut -d] -f1) 2>/dev/null;
+  }
+fi;
+
+if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
+# ui_print "Checking device...";
+  device="$(getprop ro.product.device)";
+  product="$(getprop ro.build.product)";
+  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
+    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
+    # ui_print "$testname";
+      match=1;
+      break;
+    fi;
+  done;
+  ui_print " ";
+  if [ ! "$match" ]; then
+    abort "Unsupported device. Aborting...";
+  fi;
+fi;
+
+supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
+if [ "$supported_ver" ]; then
+# ui_print "Checking Android version...";
+  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
+  if [ "$(echo $supported_ver | $bb grep -)" ]; then
+    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
+    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
+    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
+      supported=1;
+    fi;
+  else
+    for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
+      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
+        supported=1;
+        break;
+      fi;
+    done;
+  fi;
+  if [ "$supported" ]; then
+  # ui_print "$android_ver";
+    ui_print " ";
+  else
+    ui_print " ";
+    abort "Unsupported Android version. Aborting...";
+  fi;
+fi;
+
 ui_print "Installing ElectraBlue...";
 for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
+  $bb ln -s $bb bin/$i;
 done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
+if [ $? != 0 -o -z "$(ls bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
-cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
-if [ $? != "0" ]; then
-  abort "DTB append failed. Aborting...";
-fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-if [ $? != "0" ]; then
+PATH="/tmp/anykernel/bin:$PATH" $bb ash anykernel.sh $2;
+if [ $? != 0 ]; then
   abort;
 fi;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
- # ui_print " ";
- # ui_print "Pushing modules...";
-  mount -o rw,remount -t auto /system;
-  mount -o rw,remount -t auto /vendor 2>/dev/null;
+if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
+  ui_print " ";
+  ui_print "Pushing modules...";
+  $bb mount -o rw,remount -t auto /system;
+  $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd /tmp/anykernel/modules;
   for module in $(find . -name '*.ko'); do
-    if [ ! -e /$module ]; then
+    modtarget=$(echo $module | $bb cut -c2-);
+    if [ ! -e $modtarget ]; then
       case $module in
-        */vendor/*) mod=vendor;;
-        *) mod=system;;
+        */vendor/*) modcon=vendor;;
+        *) modcon=system;;
       esac;
     fi;
-    mkdir -p $(dirname /$module);
-    $bb cp -rLf $module /$module;
-    $bb chown 0:0 /$module;
-    $bb chmod 644 /$module;
-    if [ "$mod" ]; then
-      chcon "u:object_r:${mod}_file:s0" /$module;
+    if [ "$(is_mounted $modtarget)" ]; then
+      $bb mount -o rw,remount -t auto $modtarget;
+    fi;
+    mkdir -p $(dirname $modtarget);
+    $bb cp -rLf $module $modtarget;
+    $bb chown 0:0 $modtarget;
+    $bb chmod 644 $modtarget;
+    if [ "$modcon" ]; then
+      chcon "u:object_r:${modcon}_file:s0" $modtarget;
+    fi;
+    if [ "$(is_mounted $modtarget)" ]; then
+      $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
   cd /tmp/anykernel;
-  mount -o ro,remount -t auto /system;
-  mount -o ro,remount -t auto /vendor 2>/dev/null;
+  $bb mount -o ro,remount -t auto /system;
+  $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
 
 debugging;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
+if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
